### ISSUE TITLE
Instructions and recommendations for backups

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#1]
OpenOSP should help users set up backups of their MariaDB database, considering security, monitoring and regionalization (please note any other considerations)

**Comment by countable** [comment]
Instructions/testing to use this would be a good start, https://github.com/countable-web/s3-backup-jobs

instead of pg_dump, it would need to use mysql_dump

**Comment by warrendennis** [comment]
Cool. Oscar does have a backup process that is set up by the OSP with a cron job - but this script looks a lot easier.  

Do you need the Oscar backup script?

How does the awscli stuff work?

We just need to determine how, where and when the backups should be done. I guess a standard back up procedure should be written for Open OSP?

**Comment by countable** [comment]
@warrendennis I'd love to have a look at the existing backup stuff, point me there?

awscli saves the backup to S3, which is extremely redundant, very cheap (Glacier), pretty standardized (other vendors have copied S3), doesn't require a 2nd DC, and is available in Canada. But there are other options of course.

Agreed - what are your thoughts on the below?

how - either the existing periodic dump process, set up automatically of course. Or, ideally, continuous backups. I havn't looked at that for MariaDB yet. https://mariadb.com/kb/en/incremental-backup-and-restore-with-mariabackup/

where - backups should be offsite in Canada probably, on replicated affordable storage. If we are ok with Amazon (or gcloud/Azure) then S3 is pretty ideal.

when - either continuous, or approximately hourly? I'm assuming the backups don't degrade the Oscar performance during the day, if it's hourly.

**Comment by countable** [comment]
Note - in addition to the db, back up /var/lib/OscarDocument/

**Comment by countable** [comment]
Existing oscar backup process, https://oscaremr.atlassian.net/wiki/spaces/OS/pages/85727234/Backups

**Comment by countable** [comment]
@ferdinandpolpol does it make sense to start with a new backup container based on these jobs? It can just copy the backup to a local folder in the host (specified in ENV var) for now

**Comment by warrendennis** [comment]
How hard would it be to implement a SAN-like solution?  This way the back up is done in real-time in particular with the documents.

**Comment by countable** [comment]
I'm hoping the SAN would be mounted as a block device in Linux, so it would just work like any old folder from this project's perspective.

**Comment by ferdinandpolpol** [comment]
> Existing oscar backup process, https://oscaremr.atlassian.net/wiki/spaces/OS/pages/85727234/Backups

Seems like I can't find the backup.sh from the instructions.

**Comment by countable** [comment]
We also have to back up the OscarDocuments folder.
