### ISSUE TITLE
Support for Oscar 19

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#10]
use the Oscar 19 warfile and commit.

provide instructions for running open-osp for Oscar 19 intead of Oscar 15 (default).

@warrendennis which of these is actually Oscar 19 that we should use?

http://jenkins.oscar-emr.com:8080/

**Comment by countable** [comment]
@ferdinandpolpol1 please take this ticket once Dennis responds

**Comment by countable** [comment]
@warrendennis is it this one? http://jenkins.oscar-emr.com:8080/job/oscar-19.1/lastSuccessfulBuild/artifact/

**Comment by ferdinandpolpol** [comment]
created PR #56 for instruction for using Oscar 19.

**Comment by warrendennis** [comment]
Looks good.  But for the moment there is no official Release OSCAR 19 and this points to the development branch.  This is a good placeholder for when the release is available.

**Comment by ferdinandpolpol** [comment]
@warrendennis Thanks for clarifying! For other oscar versions, could you elaborate what we're gonna use? Currently in the openoscar repo, the branch with release is only Oscar15 and I'm guessing other release branches are in oscar repo?

**Comment by warrendennis** [comment]
Oscar 19 is not officially released.
We can use development for the time being.
All code is pulled from OpenOscar.
