### ISSUE TITLE
Get CI job passing. 

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#108]
https://jenkins.openosp.ca/job/openosp-health/56/console

Currently fails. We want to ignore failures until we actually reach the `openosp health` check. Any failure in this last command should then cause the Jenkins job to fail.

**Comment by ferdinandpolpol** [comment]
Got this to work! https://jenkins.openosp.ca/job/openosp-health/70/console

**Comment by countable** [comment]
Nice!

I think it's best to run on develop, where we do most of our work. Could you switch it and ensure that branch is passing?

Btw, I've also set the job to run once a day (poll scm) in the absence of any commit hook.

**Comment by ferdinandpolpol** [comment]
Changed to develop and build passed https://jenkins.openosp.ca/job/openosp-health/71/console
