### ISSUE TITLE
Auto-deploy training.openosp.ca to the latest 'stable' branch of open oscar, whenever it updates.

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#109]

**Comment by ferdinandpolpol** [comment]
Just created a job in jenkins named training. Haven't tested if it works since we don't recently have successful builds for open ocar

**Comment by ferdinandpolpol** [comment]
@countable It should be up and running now.

**Comment by countable** [comment]
Awesome, thanks! 

FYI @warrendennis
