### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#11]
our docker-compose config shoud allow providing an SSL cert file, which serves the site over HTTPs if present.

**Comment by countable** [comment]
You could generate a certbot / letsencrypt example, for testing

**Comment by ferdinandpolpol** [comment]
So we add a ssl cert file to nginx container through docker-compose and use that for `ssl_certificate` in nginx server?

**Comment by countable** [comment]
Yes, I think that's probably best so any can be used.
However, it should still work without one (or, just include a self-signed deafult cert if thats easier)
