### ISSUE TITLE
Add Melody for performance monitoring

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#130]
The instructions for enabling this are here:

http://oscarmanual.org/15/5.0/monitoring

We would want a port where we can see performance profiles for clinics.

**Comment by ferdinandpolpol** [comment]
Got a working monitoring in https://training.openosp.ca/oscar/monitoring and changes on PR #131

**Comment by countable** [comment]
Thanks @ferdinandpolpol , it would be great to also include instructions in the README for enabling optional features like this. (I've added)
