### ISSUE TITLE
OpenOSP Docker fails to install fully

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#133]
Problem:  Running ./openosp bootstrap fails at installing the FaxWs (error copied below)

Expected: All Docker containers should install successfully OR an option to install the FaxWs should be available when initiating bootstrap

Error: 
```
Step 1/11 : FROM tomcat:8.5-jre
manifest for tomcat:8.5-jre not found: manifest unknown: manifest unknown
ERROR: Service 'faxws' failed to build
Error: No such container:path: cedarwood_faxws_1:/create_database.sql
bash: _bootstrap.sql: No such file or directory
ERROR: 1
rm: cannot remove '_bootstrap.sql': No such file or directory
Setting authentication database...
ERROR 1146 (42S02) at line 1: Table 'OscarFax.users' doesn't exist
ERROR: 1
ERROR 1146 (42S02) at line 1: Table 'OscarFax.user_roles' doesn't exist
ERROR: 1
```

Problem 2:  Expedius fails to launch after running ./openosp start  (error below)

Expected:  Expedius should launch

Expedius launch error:

```
Sending build context to Docker daemon  17.41kB

Step 1/5 : FROM tomcat:8.5-jre
manifest for tomcat:8.5-jre not found: manifest unknown: manifest unknown
ERROR: Service 'expedius' failed to build
```

**Comment by itsjbecks** [comment]
Has there been any more thoughts or progress around this? I'm trying to solve this myself, but I'm a bit out of my normal stack here.

After having installed maven on my machine (macOS Big Sur 11.3), and running the build `./bin/build-faxws.sh` script I get a lot farther, but error out at 

```zsh
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project FaxWs: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:2.2:war failed: Unable to load the mojo 'war' in the plugin 'org.apache.maven.plugins:maven-war-plugin:2.2' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Cannot access defaults field of Properties
```

**Comment by lacarmen** [comment]
I think this error `Error: No such container:path: cedarwood_faxws_1:/create_database.sql` (and the following ones) comes from [this line](https://github.com/open-osp/open-osp/blob/master/bin/setup-faxws.sh#L30) of the `setup-faxws.sh` script. The container name should likely be written hyphens instead of underscores.

On my own machine, when I look at what containers I have running here's what I get
```
[~/s/open-osp] > docker ps                                                                                                                                      [ master ]
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS      NAMES
264919ea8e62   openosp/faxws:latest   "/entrypoint.sh cata…"   19 minutes ago   Up 19 minutes   8080/tcp   open-osp-faxws-1
96d78e325c06   mariadb:10.5           "docker-entrypoint.s…"   20 minutes ago   Up 20 minutes   3306/tcp   open-osp-db-1
```

Note the container name `open-osp-faxws-1`.

Changing the line that I linked to `docker cp ${dcid}-faxws-1:/create_database.sql _bootstrap.sql` allows the script to complete successfully for me.

**Comment by itsjbecks** [comment]
For what it's worth, my solution has been to just run `./openosp build faxws` before the bootstrap command and it works consistently. Obviously not a solution, but a workaround.

**Comment by lacarmen** [comment]
@warrendennis regarding your expedius error, this can be fixed by changing the image name in the expedius Dockerfile to `FROM tomcat:8.5-jre8` (note the 8).

I see @itsjbecks actually submitted [a fix](https://github.com/open-osp/open-osp/pull/141) for this last month 🙌

**Comment by lacarmen** [comment]
Ohhh... I think I know why the faxws and mariadb containers are named with hyphens while oscar and expedius are named with underscores...

```
[~/s/open-osp] > docker ps                                                                                                                                    ± [ master ]
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                          PORTS                    NAMES
a380520ef110   openosp/expedius:latest   "catalina.sh run"        2 minutes ago    Restarting (1) 20 seconds ago                            open-osp_expedius_1
b47401c89c5c   openosp/open-osp:latest   "/entrypoint.sh /sta…"   3 minutes ago    Up 3 minutes                    0.0.0.0:8080->8080/tcp   open-osp_oscar_1
264919ea8e62   openosp/faxws:latest      "/entrypoint.sh cata…"   36 minutes ago   Up 36 minutes                   8080/tcp                 open-osp-faxws-1
96d78e325c06   mariadb:10.5              "docker-entrypoint.s…"   37 minutes ago   Up 37 minutes                   3306/tcp                 open-osp-db-1
```

 [`openosp-start.sh`](https://github.com/open-osp/open-osp/blob/master/bin/openosp-start.sh) calls `docker-compose` with the `--compatibility` flag. While `openosp-bootstrap.sh` and `setup-fax.sh` do not... 🤔
