### ISSUE TITLE
For New MariaDB setups, disable default user expiry

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#15]
This is not a useful security feature in our setup. Run this after creating the DB,

mysql -uroot -pliyi oscar_12_1
update security set date_ExpireDate=DATE_ADD(CURDATE(), INTERVAL 360 MONTH), b_ExpireSet=1 where user_name='oscardoc';
quit;

**Comment by warrendennis** [comment]
Yep. Not a good idea to deploy that. This should be changed in the schema
