### ISSUE TITLE
OSCAR fails to build on first launch

### ISSUE THREAD

**Issue by openosp** [open-osp/open-osp#152]
The openosp start command fails when building a fresh Docker environment.  The OSCAR container is not deployed and the start command returns this error: 

Step 8/25 : ADD oscar.war /usr/local/tomcat/webapps/oscar.war
ERROR: Service 'oscar' failed to build: ADD failed: file not found in build context or excluded by .dockerignore: stat oscar.war: file does not exist

**Comment by countable** [comment]
Hmm... a fresh clone and build is working for me. Can you provide exact commands?

I'm doing this:
 $  git clone https://github.com/open-osp/open-osp
 $  cd open-osp
 $  openosp setup --noinput
 $  openosp bootstrap
 $  d up -d expedius oscar

**Comment by openosp** [comment]
Dear open-osp/open-osp,

Your support ticket "Re: [open-osp/open-osp] OSCAR fails to build on first launch (Issue #1" has been submitted.

We reply to all tickets as soon as possible, within 24 to 48 hours. If we expect your ticket will take additional time, we will update you by sending you an email.

Ticket tracking ID: QDN-DSV-UPQT

You can view the status of your ticket here:
https://support.openosp.ca/ticket.php?track=QDN-DSV-UPQT&e=reply%2BAW3TUTY3TMBRBQ376PJX2BWAMODDVEVBNHHEKUZMNM%40reply.github.com&Refresh=44916 

You will receive an email notification when our staff replies to your ticket.


Sincerely,

Open OSP Support
https://support.openosp.ca

**Comment by countable** [comment]
Actually, I think I see. It's trying to build because it's missing images, and that fails.

You probably want to `docker pull openosp/open-osp` first to prevent this.

**Comment by openosp** [comment]
Dear open-osp/open-osp,

Your support ticket "Re: [open-osp/open-osp] OSCAR fails to build on first launch (Issue #1" has been submitted.

We reply to all tickets as soon as possible, within 24 to 48 hours. If we expect your ticket will take additional time, we will update you by sending you an email.

Ticket tracking ID: LNL-49T-TMSU

You can view the status of your ticket here:
https://support.openosp.ca/ticket.php?track=LNL-49T-TMSU&e=reply%2BAW3TUT7U5L3WF5TLWCFSZB6AMODI7EVBNHHEKUZMNM%40reply.github.com&Refresh=40914 

You will receive an email notification when our staff replies to your ticket.


Sincerely,

Open OSP Support
https://support.openosp.ca
