### ISSUE TITLE
OSCAR Pro Build Fails

### ISSUE THREAD

**Issue by JamesGrayson** [open-osp/open-osp#153]
Hello,

I have been trying to run `./openosp build oscar` with the `OSCAR_TREEISH` variable set to `master`, and the `OSCAR_REPO` variable set to `https://bitbucket.org/oscaremr/oscarpro.git`. While everything is cloned just fine from the OSCAR Pro bitbucket repository, the maven build fails with a 

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /code/docker/oscar/oscar/src/main/java/org/oscarehr/billing/CA/ON/web/RASummaryAction.java:[28,7] error: class RaSummaryAction is public, should be declared in a file named RaSummaryAction.java
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.942 s
[INFO] Finished at: 2022-03-14T23:24:46Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project kai-15-pilot: Compilation failure
[ERROR] /code/docker/oscar/oscar/src/main/java/org/oscarehr/billing/CA/ON/web/RASummaryAction.java:[28,7] error: class RaSummaryAction is public, should be declared in a file named RaSummaryAction.java
```

It would seem that OSCAR Pro isn't supported as there isn't any mention of it in the README, but are there any plans to add support to OSCAR Pro? Having the ability to easily switch between different versions of 15, 19, and Pro would be cool for a testing environment.

Thanks.

**Comment by warrendennis** [comment]
Hi James;

This is a Docker repository that facilitates deployment of a variety of **stable** OSCAR EMR software onto Linux servers.  This error appears to be a flaw or missing resource in the OSCAR Pro software.  We do not support errors in any of the software being deployed by Docker.  

Please report this error to the maintainers of OSCAR Pro.
