### ISSUE TITLE
FaxWS not setting up on deployment

### ISSUE THREAD

**Issue by openosp** [open-osp/open-osp#162]
The FaxWS authentication database does not set up correctly on first deployment. 

These errors are found? 

Creating oscarfive_faxws_1 ... done
No such command: cp

Commands:
  build              Build or rebuild services
  config             Validate and view the Compose file
  create             Create services
  down               Stop and remove resources
  events             Receive real time events from containers
  exec               Execute a command in a running container
  help               Get help on a command
  images             List images
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pull service images
  push               Push service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  top                Display the running processes
  unpause            Unpause services
  up                 Create and start containers
  version            Show version information and quit
bash: _bootstrap.sql: No such file or directory
ERROR: 1
rm: cannot remove '_bootstrap.sql': No such file or directory
Setting authentication database...
ERROR 1146 (42S02) at line 1: Table 'OscarFax.users' doesn't exist
ERROR: 1
ERROR 1146 (42S02) at line 1: Table 'OscarFax.user_roles' doesn't exist
ERROR: 1

**Comment by fredngo** [comment]
@openosp What command did you run to generate these errors?

I'll check it out if you can tell me how to replicate.

By the way, who is @openosp ?

**Comment by openosp** [comment]
Dear open-osp/open-osp,

Your support ticket "Re: [open-osp/open-osp] FaxWS not setting up on deployment (Issue #162" has been submitted.

We reply to all tickets as soon as possible, within 24 to 48 hours. If we expect your ticket will take additional time, we will update you by sending you an email.

Ticket tracking ID: 7YG-AP5-71Q5

You can view the status of your ticket here:
https://support.openosp.ca/ticket.php?track=7YG-AP5-71Q5&e=reply%2BAW3TUT3PFOE63BD3PH2YQAGBRYNQ7EVBNHHFLYU2KA%40reply.github.com&Refresh=31244 

You will receive an email notification when our staff replies to your ticket.


Sincerely,

Open OSP Support
https://support.openosp.ca

**Comment by fredngo** [comment]
Please try this command and let me know what it says:

```
git log --oneline bin/setup-faxws.sh | head -2
```

It **should** say:

```
d093f72 Use docker-compose to copy a file out of the currently container instead of manually hacking together the container name
867d0af origin/dashes-over-underscores
```

**Comment by openosp** [comment]
Dear open-osp/open-osp,

Your support ticket "Re: [open-osp/open-osp] FaxWS not setting up on deployment (Issue #162" has been submitted.

We reply to all tickets as soon as possible, within 24 to 48 hours. If we expect your ticket will take additional time, we will update you by sending you an email.

Ticket tracking ID: LWS-7LZ-PR58

You can view the status of your ticket here:
https://support.openosp.ca/ticket.php?track=LWS-7LZ-PR58&e=reply%2BAW3TUT6XJ6G6FLS3RUJZDLWBRYPI7EVBNHHFLYU2KA%40reply.github.com&Refresh=36410 

You will receive an email notification when our staff replies to your ticket.


Sincerely,

Open OSP Support
https://support.openosp.ca

**Comment by openosp** [comment]
Dear open-osp/open-osp,

We have just replied to your ticket "Re: [open-osp/open-osp] FaxWS not setting up on deployment (Issue #162".

To read the message, submit a reply and view details, please visit:
https://support.openosp.ca/ticket.php?track=7YG-AP5-71Q5&e=reply%2BAW3TUT3PFOE63BD3PH2YQAGBRYNQ7EVBNHHFLYU2KA%40reply.github.com&Refresh=97477 

If the above link is not clickable, try copying and pasting it into the address bar of your web browser.

Sincerely,

Open OSP Support
https://support.openosp.ca

**Comment by warrendennis** [comment]
stale issue
