### ISSUE TITLE
db_password not being populated in volumes/drugref2.properties resulting in drugref not working

### ISSUE THREAD

**Issue by adrianaditech** [open-osp/open-osp#171]
`JavaClient: XML-RPC Fault #0: org.apache.xmlrpc.XmlRpcException: java.lang.Exception: org.apache.openjpa.persistence.PersistenceException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'open-osp_oscar_1.open-osp_back-tier' (using password: NO))`
due to openosp setup not populating the db_password in the volumes/drugref2.properties. Have to insert the mysql root password manually here for the drugref to work.

**Comment by warrendennis** [comment]
thank you. patch applied to master

**Comment by adrianaditech** [comment]
> thank you. patch applied to master

@warrendennis  the installation script is still not populating the password in drugref2.properties, resulting in same error.
