### ISSUE TITLE
Waiting for database connection. shell script did not complete

### ISSUE THREAD

**Issue by aetiologicCanada** [open-osp/open-osp#18]
Script did not complete:

``
rob@linuxmachine:~/Rprojects/Projects/open-osp$  ./deploy-release.sh 
allexport       off
braceexpand     on
emacs           off
errexit         on
errtrace        off
functrace       off
hashall         on
histexpand      off
history         off
ignoreeof       off
interactive-comments    on
keyword         off
monitor         off
noclobber       off
noexec          off
noglob          off
nolog           off
notify          off
nounset         on
onecmd          off
physical        off
pipefail        off
posix           off
privileged      off
verbose         off
vi              off
xtrace          on
+ export OSCAR_TREEISH=97292c71a3af47e0539b2b7336b9b06f16b8b090
+ OSCAR_TREEISH=97292c71a3af47e0539b2b7336b9b06f16b8b090
+ docker-compose run builder ./bin/clone.sh
Creating network "openosp_default" with the default driver
Creating network "openosp_back-tier" with driver "bridge"
Creating volume "openosp_mariadb-files" with local driver
Pulling builder (openjdk:8)...
8: Pulling from library/openjdk
146bd6a88618: Pull complete
9935d0c62ace: Pull complete
db0efb86e806: Pull complete
e705a4c4fd31: Pull complete
3d3bf7f7e874: Pull complete
49371c5b9ff6: Pull complete
3f7eaaf7ad75: Pull complete
Digest: sha256:7b7408b997615b4d6aaf6c1f0de8a32182497250288ee0a27b4e98cf14a52fb3
Status: Downloaded newer image for openjdk:8
allexport       off
braceexpand     on
emacs           off
errexit         off
errtrace        off
functrace       off
hashall         on
histexpand      off
history         off
ignoreeof       off
interactive-comments    on
keyword         off
monitor         off
noclobber       off
noexec          off
noglob          off
nolog           off
notify          off
nounset         on
onecmd          off
physical        off
pipefail        off
posix           off
privileged      off
verbose         off
vi              off
xtrace          on
+ branch=97292c71a3af47e0539b2b7336b9b06f16b8b090
+ repo=https://bitbucket.org/oscaremr/oscar.git
+ echo 'Cloning oscar from bitbucket'
Cloning oscar from bitbucket
+ '[' -d ./oscar ']'
+ git clone https://bitbucket.org/oscaremr/oscar.git oscar
Cloning into 'oscar'...
remote: Counting objects: 383046, done.
remote: Compressing objects: 100% (130581/130581), done.
remote: Total 383046 (delta 285771), reused 322244 (delta 245176)
Receiving objects: 100% (383046/383046), 329.32 MiB | 17.08 MiB/s, done.
Resolving deltas: 100% (285771/285771), done.
Checking out files: 100% (10625/10625), done.
+ cd oscar
+ git checkout 97292c71a3af47e0539b2b7336b9b06f16b8b090
Note: checking out '97292c71a3af47e0539b2b7336b9b06f16b8b090'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 97292c71a3... Merged in OSCAREMR-6845-printing-of-labs-with-embe (pull request #588)
+ ./bin/run.sh
Setting up database...
Pulling db (mariadb:10.4)...
10.4: Pulling from library/mariadb
5c939e3a4d10: Pull complete
c63719cdbe7a: Pull complete
19a861ea6baf: Pull complete
651c9d2d6c4f: Pull complete
077e14009561: Pull complete
5f038f59a326: Pull complete
1b0216466f21: Pull complete
1b0570aa273a: Pull complete
07d05628c2aa: Pull complete
8f2f7d8e5cbd: Pull complete
a3b7bdee82b3: Pull complete
dd5eb2e45b9a: Pull complete
ca8c80c59b5a: Pull complete
4df3d7f35a25: Pull complete
Digest: sha256:709465024f7d574afae9501f163fb7406c25fdb74a8baf2663dd3adc0069d9d3
Status: Downloaded newer image for mariadb:10.4
Creating openosp_db_1 ... 
Creating openosp_db_1 ... done
Waiting for db containers to initialize (1 min)
Waiting for database connection...
.. about 50 lines deleted---
Waiting for database connection...
Waiting for database connection...
^C^C
rob@linuxmachine:~/Rprojects/Projects/open-osp$ 
```

**Comment by countable** [comment]
It should wait there for 20 seconds at most. If it's hanging a long time, that means your db container is not coming up. When it's in this state, open another shell in the same folder. What do these commands output?

```
docker-compose logs db
docker-compose ps
```

Is the DB container crashed?

**Comment by countable** [comment]
@aetiologicCanada I've just run this and it does take a long time on my other laptop, about 1 to 2 minutes. If you wait 5 minutes is it still hanging?

**Comment by countable** [comment]
If you get stuck, run `./purge.sh` and start over.

**Comment by ferdinandpolpol** [comment]
@countable I still get this issue from time to time. Some steps I do to pass this issue are:

- Press `ctrl + c` to cancel if experiencing the issue.
- Comment out `mariadb-files` from `db` in `docker-compose.yml`
- `./bin/setup.sh`
