### ISSUE TITLE
Expose the local properties file in a web UI

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#27]
Run a small service, such as flask, to allow editing open-osp/oscar_mcmaster_bc.properties directly in the browser.

This is the local copy of the properties file the build produces.

a textarea and a save button is fine for now

**Comment by countable** [comment]
This will need some basic authentication of course. A hardcoded username and password from local.env can be a starting point.

**Comment by warrendennis** [comment]
Any thing that displays markup would be ideal.

**Comment by warrendennis** [comment]
Sorry - markdown.

**Comment by countable** [comment]
The properties file isn't markdown, is it? I thought it's just a config file.

**Comment by warrendennis** [comment]
Technically it’s a Properties file being used as a config file. 

I don’t see any reason why it wouldn’t display as markdown.  Markdown headings are no different than properties comments.

**Comment by ferdinandpolpol** [comment]
Opened a PR WIP #28
