### ISSUE TITLE
Integrator Support

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#33]
The integrator is a service for sharing data between clinics. We just need to run it in a new service (container) for now (or inside the existing tomcat_oscar as a separate .war as drugref)

@warrendennis please provide instructions for setting up the Integrator.

Countable will Dockerize this as part of OpenOSP.

**Comment by warrendennis** [comment]
Very low on the priority list for now.

**Comment by warrendennis** [comment]
stale feature request
