### ISSUE TITLE
Locale not being set correctly

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#67]
The locale is not being set in the Docker containers correctly.  This causes JAVA to misinterpret dollar signs in Oscar's billing module.  At the moment the generic UTF character for a dollar sign is being displayed and printed on all customer invoices. 
Please set the locale to match the container's host or explicitly set it to en_US.UTF-8
<img width="530" alt="Screen Shot 2020-04-23 at 6 21 07 PM" src="https://user-images.githubusercontent.com/11879335/80165389-3dfd0b80-8590-11ea-991a-5f84f816eed4.png">

**Comment by warrendennis** [comment]
Also please update the currently running installs with the correct locale.

**Comment by countable** [comment]
There shouldn't be any dependency on the host's locale, we should explicitly set the locale to what it should be for Oscar. ie)

# Set the locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

**Comment by warrendennis** [comment]
Is it possible to set the local correctly on the OSCAR instances that are already in production?  ie: Monk .  They are still suffering from the side effects and would be very thankful when it's fixed.

**Comment by warrendennis** [comment]
Please adjust the local in all the current production systems. Or provide a script that I use to help.

**Comment by countable** [comment]
This is duplicated, with more information in the other copy.
