### ISSUE TITLE
Incorrect Configurations for Expedius

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#69]
These observations are based on the most recent install at NWFPPAC. 

1.) Expected URL does not redirect to Expedius.  The URL should be: xxxx.openosp.ca/Expedius  NOT xxxx.openosp.ca:<port>/Expedius

2.) URL fails when using HTTPS to connect with the Expedius GUI: Secure Connection Failed Error code: SSL_ERROR_RX_RECORD_TOO_LONG.  A secure connection is required.

3.) Expedius is accessible via the root DNS. ie: <root server dns>:<port>/Expedius.  

4.) 2 different user credentials are added to the tomcat-users file during install.  These credentials cause a conflict. Only 1 is required.

**Comment by warrendennis** [comment]
Now Im not sure about the tomcat-users.xml file.  It looks like 3 different files were installed. 2 are inside the Expedius container and 1 is in the Volumes directory.

**Comment by countable** [comment]
3 different files? As in 3 versions of server.xml? 

Please note that we are not running tomcat apps together anymore, and expedius will run on a different port than the main Oscar. Ideally IMO an administrative web app should not be exposed at all in the long term. It's not automatable, an is unnecessary attack surface.

**Comment by warrendennis** [comment]
> 3 different files? As in 3 versions of server.xml?

No. As in 3 different versions of tomcat-users.xml

> Please note that we are not running tomcat apps together anymore, and expedius will run on a different port than the main Oscar. Ideally IMO an administrative web app should not be exposed at all in the long term. It's not automatable, an is unnecessary attack surface.

Understood.  Expedius has an administrative user interface that needs to be available to the user - just like Oscar or any other 3rd party application.  This is not an unusual or insecure feature.

**Comment by warrendennis** [comment]
Alternatively we could shut off the user interface.  Then we would need to add additional Docker scripts that can configure and launch Expedius as it is needed (instead of 1 big package):

1.) convert PFX certificate
2.) install bi-directional SSL security
3.) enable Excelleris account login information
4.) enable Oscar API access. 

SSH access - in place of the user interface - will be needed to adjust the various settings for the service as needed, such as: 

1.) lab retrieval cycles
2.) changes to Excelleris username and password
3.) updates for each clients Excelleris security certificate.

These settings could be available in the general control panel that is planned for future development.

**Comment by warrendennis** [comment]
For the time being. We just need Expedius/Excelleris to work dependably as there is a higher risk of medical doctors not receiving important lab documents.

**Comment by warrendennis** [comment]
More details on the set-up of the Expedius tomcat-users.xml files;
 
1.)  the tomcat-users.xml file in the volumes directory contains 2 active Expedius user accounts (see screen shot)

<img width="814" alt="Screen Shot 2020-05-15 at 2 05 44 PM" src="https://user-images.githubusercontent.com/11879335/82096520-03315380-96b6-11ea-9228-a3693a5ab383.png">

2.) there is an additional tomcat-users.xml file in the config folder of the Expedius container. 

3.) how do we know which Tomcat container (OSCAR, FaxWs, or Expedius) the tomcat-users.xml contained in the volumes directory is for? 

This current set-up breaks the feature. Only 1 tomcat-users.xml file with only 1 user is required.

**Comment by warrendennis** [comment]
A PR has been submitted for issue number 4. 
The user facing gui still needs to be secured.
