### ISSUE TITLE
Manager App Should be Disabled in all Tomcat Installs

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#70]
The default installs of Tomcat include an application called Manager.  This application is not needed for our purposes. It only adds clutter and it argumentatively weakens security in production environments. 

The Manager App should be disabled in all installs of Tomcat.  Details about Manager are here: http://tomcat.apache.org/tomcat-8.0-doc/manager-howto.html#Introduction

One of many good tutorials on hardening Tomcat and removing the Manager clutter is here: https://geekflare.com/apache-tomcat-hardening-and-security-guide/

Please add these procedures to the install process.

**Comment by warrendennis** [comment]
I noticed that the official Docker Tomcat image just recently started to harden Tomcat by default.  This ticket can be resolved if the Official Docker Tomcat Image is being used going forward.

**Comment by ferdinandpolpol** [comment]
I tried using 9-jre8 image for oscar and this shows up when trying to access /manager. Is this the behavior we want to happen?
![image](https://user-images.githubusercontent.com/26404494/82230597-c9906080-98e0-11ea-9865-a313a86ebe0c.png)

**Comment by warrendennis** [comment]
Hi Ferdinand;

We don't want the Manager at all. Rip out all the files if you need to.  The official Tomcat Docker build #181 (tomcat:9.0) should not install any part of the Manager. 

Note: as of docker-library/tomcat#181 <https://github.com/docker-library/tomcat/pull/181>, the upstream-provided (example) webapps are not enabled by default, per upstream's security recommendations <https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications>, but are still available under the webapps.dist folder within the image to make them easier to re-enable.

Feel free to delete the webapps.dist directory before deployment too.

More details on Tomcat security here: https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications <https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications>

**Comment by ferdinandpolpol** [comment]
Closing this since this is already merged
