### ISSUE TITLE
Accessible Logging

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#71]
Logs are not being retained and/or they are not accessible in production environments.  This makes diagnosis for bugs very difficult.  Tailing live logs from the Docker container is not helpful. 

Catalina.out is the preferred "catch all" log if other logging methods are not available.  A standard retention period of 30 days with daily log splicing is also preferred.

**Comment by countable** [comment]
persistent logging is added on aws1, it's just needed on the new node, aws2

**Comment by warrendennis** [comment]
The current Oscar 15 release has been patched.  Initial testing has **failed**.  All IP addresses still resolve to AWS2.  Other cloud hosted Oscar services don't seem to have this issue (confirmed directly).
