### ISSUE TITLE
DrugRef Install Needs Data

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#72]
Please adjust the install scripts so that DrugRef loads all the medication data.  Contact me for details when this ticket is picked.

**Comment by warrendennis** [comment]
Hi Ferdinand;
DrugRef is a mini XML-RPC server.  Status and update calls can be done with curl AFTER DrugRef and its database has been configured and deployed.  

Create the XML request:

`<?xml version="1.0" ?>
<methodCall>
  <methodName>updateDB</methodName>
</methodCall>`

Save the XML as updatedrugref.xml (or whatever you wish). Then use curl to execute it:

`curl -v -H "content-type:text/xml" http://localhost:8080/drugref2/DrugrefService --data @updatedrugref.xml` 

I'm guessing that localhost:8080 would be replaced with the Docker container name, ie: drugref:8080.

A positive response is:

`<?xml version="1.0"?> <methodResponse> <params><param><value>running</value></param></params></methodResponse>`

**The actual update process can take up-to 2 hours** - so - it is best if this is the last task in the total deployment so that the database and DrugRef containers are not shutdown or restarted.

### Other Useful Commands

To get the last update date/time:

`<?xml version="1.0" ?>
<methodCall>
  <methodName>getLastUpdateTime</methodName>
</methodCall>`

Test search function by searching for "CARBIDOPA":

`<?xml version="1.0" ?>
<methodCall>
  <methodName>list_search_element</methodName>
      <params>
         <param>
            <value>CARBIDOPA</value>
         </param>
      </params>
</methodCall>`

**Comment by ferdinandpolpol** [comment]
Created a PR #84
