### ISSUE TITLE
Fix the Time Zone to Pacific

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#76]
The internal time zone on the PCN EMR is off.  Probably set for ON time. It's now 10:44 p. m., May 16, 2020; and the date stamp on my eFORMS says May 17/2020.

Please fix this for future installs and all the installs currently in production.

**Comment by ferdinandpolpol** [comment]
@warrendennis When I create a new eform and show the date it seems to be in the correct date. How do I reproduce the issue? 
![image](https://user-images.githubusercontent.com/26404494/82471816-165c6e80-9a7c-11ea-98a1-13e5e372c65e.png)

**Comment by warrendennis** [comment]
@Ferdinand

Unfortunately the problem is a little more complicated.  Try this in a new eform:
 

<input name="today" id="today" type="text" class="noborder"  oscardb=today>

<input name=“time" id=“time" type="text" class="noborder"  oscardb=time>


Those oscardb attributes trigger a SELECT curdate() on the Oscar database.  We need to ensure that the database image is also deployed with the correct local and timezone settings.

**Comment by countable** [comment]
Looks like we gotta do: https://stackoverflow.com/questions/49959601/configure-time-zone-to-mysql-docker-container

**Comment by countable** [comment]
Apparently this works on the Oscar side, connection string. I'm setting these, please confirm if it worked. `&serverTimezone=America/Vancouver`

**Comment by warrendennis** [comment]
Does not work database time is still incorrect.  Putting that parameter in the connection string will not set the database to the correct time.   The database sets its own time from its environment.
