### ISSUE TITLE
jenkins slave

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#78]
Set up a new slave on

15.222.244.42

run all CI jobs (open-oscar) and (open-osp) to do full build with health check/tests to indicate success, on any branch, and post to open-oscar slack.

**Comment by countable** [comment]
run dotfiles and connect jenkins to the new node

**Comment by ferdinandpolpol** [comment]
@countable there are failures when we do ./openosp scripts. It seems this happens because it is waiting for input?

**Comment by countable** [comment]
Yes, can you add a "--noinput" switch to openosp, so it just skips the prompts (leaves them blank)
