### ISSUE TITLE
cert issue when faxws talks to oscar

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#79]
see comment below.

**Comment by countable** [comment]
@warrendennis please instruction on setting up key trust store in oscar to trust faxws

**Comment by warrendennis** [comment]
To trust an OSCAR cert in the FaxWs container:

1.) from inside the FaxWs container, fetch the OSCAR cert

openssl s_client -showcerts -connect o <http://nwfppac.openosp.ca/>scar:443 oscar_scbp</dev/null 2>/dev/null|openssl x509 -outform PEM > oscar.pem

2.) add the cert to the FaxWs cacerts truststore

keytool -importcert -alias oscar -keystore /usr/local/openjdk-8/jre/lib/security/cacerts -storepass changeit -file oscar.pem


To trust an FaxWs cert in the OSCAR container: 

1.) from inside the OSCAR container, fetch the FaxWs cert

openssl s_client -showcerts -connect o <http://nwfppac.openosp.ca/>scar:443 oscar_scbp</dev/null 2>/dev/null|openssl x509 -outform PEM > oscar.pem

2.) add the cert to the OSCAR cacerts truststore

keytool -importcert -alias faxws -keystore /usr/local/openjdk-8/jre/lib/security/cacerts -storepass changeit -file faxws.pem

Assumptions

that JAVA HOME is at /usr/local/openjdk-8.  It may be best to set the JAVA HOME variable on the outset. 
the truststore path that Tomcat is using is tied into /jre/lib/security/cacerts.  Some servers miss including this truststore at /etc/ssl/certs/java/cacerts

**Comment by warrendennis** [comment]
WARNING: this method may not work if the certificate domain names dont match up.

**Comment by countable** [comment]
added in master
