### ISSUE TITLE
common base image for services

### ISSUE THREAD

**Issue by countable** [open-osp/open-osp#80]
Oscar, faxws and expedius should all use the same Docker tomcat base image. Currently oscar uses tomcat:7-jre8 and the others use plain tomcat:7

**Comment by warrendennis** [comment]
I think I see the potential conflict here.  Dockers tomcat 7 doesnt appear to be security hardened whereas Tomcat 9 is (?).  Above all else all images should be using identical versions of java and tomcat from the same image source and they should all be security hardened according to Apaches recommendations: http://tomcat.apache.org/tomcat-7.0-doc/security-howto.html
The Manager App should not be installed as it is not required.

**Comment by countable** [comment]
The images all use a common Java base now
