### ISSUE TITLE
Root DNS Exposes Tomcat Manager App

### ISSUE THREAD

**Issue by warrendennis** [open-osp/open-osp#81]
The most recent install at training.openosp.ca now exposes the Tomcat Manager app when the main DN is used (screenshot below).  

### Problem:

1.) this is considered broken to end user because they are not currently aware that they need to add the context path for Oscar ie: training.openosp.ca/oscar

2.) The Tomcat Manager app should not be available at all.  Nothing more than a 404 should be found at the root context. 

### Recommended solutions: 

1.) the DN training.openosp.ca should be identified as an alias (CNAME) for training.openosp.ca/oscar in NGINX or HAProxy.  DO NOT use a redirect in the ROOT as we suspect this is causing some issues with the session and security. 

2.) Find a pre-configured production Tomcat image in Docker hub OR consider adding steps to harden Tomcat during deployment.  Removal of, or avoidance to install, the Tomcat Manager app is considered a good security practice. It also lightens Tomcats footprint on the server. 

Official Tomcat security guide: http://tomcat.apache.org/tomcat-7.0-doc/security-howto.html
Unofficial tutorial: https://geekflare.com/apache-tomcat-hardening-and-security-guide/

<img width="1148" alt="Screen Shot 2020-05-22 at 12 26 00 PM" src="https://user-images.githubusercontent.com/11879335/82702801-907d2680-9c27-11ea-8258-8b408db471f8.png">

**Comment by countable** [comment]
fixed in master
